<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.arange(15).reshape(3,5)
a



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape


(3, 5)

In [0]:
a.ndim

2

In [0]:
a.dtype.name

'int64'

In [0]:
a.itemsize

8

In [0]:
a.size

15

In [0]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [0]:
type(b)

numpy.ndarray

In [0]:
import numpy as np
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [0]:
a.ndim

3

In [0]:
a.dtype.name

'int64'

In [0]:
a.size

12

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [0]:
type(b)


numpy.ndarray

In [0]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [0]:
a.dtype

dtype('int64')

In [0]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [5]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [6]:
a.dtype

dtype('int64')

In [7]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [8]:
b=np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [16]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])