<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.arange(15).reshape(3,5)
a



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape


(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.itemsize

8

In [7]:
a.size

15

In [9]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

In [15]:
import numpy as np
a=np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [16]:
a.ndim

3

In [17]:
a.dtype.name

'int64'

In [18]:
a.size

12

In [19]:
type(a)

numpy.ndarray

In [20]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [21]:
type(b)


numpy.ndarray

In [23]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [24]:
a.dtype

dtype('int64')

In [25]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

In [0]:
b=np.array([(1.5,2,3),(4,5,6)])
b