<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/bo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [0]:
c=a-b
c

array([20, 29, 38, 47])

In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a<35

array([ True,  True, False, False])

In [0]:
A=np.array([[1,1],
           [0,1]])
B=np.array([[2,0],
            [3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [0]:
A@B

array([[5, 4],
       [3, 4]])

In [0]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
b+=a
b

array([[3.16063883, 3.22925264, 3.36852383],
       [3.70493588, 3.89081823, 3.32048295]])

In [0]:
a+=b


In [0]:
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [0]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [0]:
c.dtype.name

'float64'

In [0]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [0]:
d.dtype.name

'complex128'

In [0]:
a=np.random.random((2,3))
a

array([[0.59192808, 0.89022708, 0.4714609 ],
       [0.22079979, 0.32409181, 0.48859424]])

In [0]:
a.sum()

2.987101899586298

In [0]:
a.min()

0.2207997946448177

In [0]:
a.max()

0.8902270776541363

In [0]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [0]:
b.min(axis=1)

array([0, 4, 8])

In [0]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

UNIVERSAL FUNCTIONS

In [7]:
import numpy as np
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [20]:
np.max(b)

4

In [22]:
np.nonzero(b)

(array([1, 2, 3, 4]),)

In [18]:
c=np.array([2.,-1.,4.,6.,8.])
np.add(b,c)

array([ 2.,  0.,  6.,  9., 12.])

INDEXING SLICING ITERATING

In [23]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [27]:
a[-2]

512

In [42]:
a[2:5]

array([ 8, 27, 64])

In [44]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [45]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [46]:
for i in a:
  print(i**(1/3))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


MULTIDIMENSIONAL

In [49]:
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [55]:
b[2,3]

23

In [60]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [61]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [65]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [66]:
b[-1]

array([40, 41, 42, 43])

In [67]:
c=np.array([[[0,1,2],
             [10,12,13]],
            [[100,101,102],
            [110,112,113]]])
c.shape

(2, 2, 3)

N DIMENSIONAL ARRAY

In [69]:
np.array(8)

array(8)

In [70]:
np.array([2.3,0.1,-9.1])

array([ 2.3,  0.1, -9.1])

In [0]:
d3_array=np.array([[[0,1],
                  [2,3]],
                   
                  [[4,5],
                   [6,7]]])

In [90]:
d3_array[1,0,1]

5

In [78]:
d3_array[:,0,0]

array([0, 4])

In [92]:
d3_array[0]

array([[0, 1],
       [2, 3]])

In [93]:
d3_array[1]

array([[4, 5],
       [6, 7]])

3 DIMENSIONAL

In [0]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
             [[9,10,11],
              [12,13,14],
              [15,16,17]],
              
              [[18,19,20],
               [21,22,23],
               [24,25,26]]])

In [100]:
x.item()

15.2

In [0]:
x=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])

In [107]:
x.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [112]:
c=np.array ([[[0,1,2],
            [10,12,13]],
             
            [[100,101,102],
            [110,112,113]]])
c.shape

(2, 2, 3)

In [114]:
c[0,...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [117]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [119]:
c[...,2]

array([[  2,  13],
       [102, 113]])