<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/bo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [0]:
c=a-b
c

array([20, 29, 38, 47])

In [0]:
b**2

array([0, 1, 4, 9])

In [0]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [0]:
a<35

array([ True,  True, False, False])

In [0]:
A=np.array([[1,1],
           [0,1]])
B=np.array([[2,0],
            [3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [0]:
A@B

array([[5, 4],
       [3, 4]])

In [0]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [0]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
b+=a
b

array([[3.16063883, 3.22925264, 3.36852383],
       [3.70493588, 3.89081823, 3.32048295]])

In [0]:
a+=b


In [0]:
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [0]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [0]:
c.dtype.name

'float64'

In [0]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [0]:
d.dtype.name

'complex128'

In [0]:
a=np.random.random((2,3))
a

array([[0.59192808, 0.89022708, 0.4714609 ],
       [0.22079979, 0.32409181, 0.48859424]])

In [0]:
a.sum()

2.987101899586298

In [0]:
a.min()

0.2207997946448177

In [0]:
a.max()

0.8902270776541363

In [0]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [0]:
b.min(axis=1)

array([0, 4, 8])

In [0]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

UNIVERSAL FUNCTIONS

In [0]:
import numpy as np
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [0]:
np.max(b)

4

In [0]:
np.nonzero(b)

(array([1, 2, 3, 4]),)

In [0]:
c=np.array([2.,-1.,4.,6.,8.])
np.add(b,c)

array([ 2.,  0.,  6.,  9., 12.])

INDEXING SLICING ITERATING

In [0]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[-2]

512

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [0]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [0]:
for i in a:
  print(i**(1/3))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


MULTIDIMENSIONAL

In [0]:
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
b[2,3]

23

In [0]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [0]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [0]:
b[-1]

array([40, 41, 42, 43])

In [0]:
c=np.array([[[0,1,2],
             [10,12,13]],
            [[100,101,102],
            [110,112,113]]])
c.shape

(2, 2, 3)

N DIMENSIONAL ARRAY

In [0]:
np.array(8)

array(8)

In [0]:
np.array([2.3,0.1,-9.1])

array([ 2.3,  0.1, -9.1])

In [0]:
d3_array=np.array([[[0,1],
                  [2,3]],
                   
                  [[4,5],
                   [6,7]]])

In [0]:
d3_array[1,0,1]

5

In [0]:
d3_array[:,0,0]

array([0, 4])

In [0]:
d3_array[0]

array([[0, 1],
       [2, 3]])

In [0]:
d3_array[1]

array([[4, 5],
       [6, 7]])

3 DIMENSIONAL

In [0]:
arr=np.array([[[0,1,2],
              [3,4,5],
              [6,7,8]],
              
             [[9,10,11],
              [12,13,14],
              [15,16,17]],
              
              [[18,19,20],
               [21,22,23],
               [24,25,26]]])

In [0]:
x.item()

15.2

In [0]:
x=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])

In [0]:
x.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [0]:
c=np.array ([[[0,1,2],
            [10,12,13]],
             
            [[100,101,102],
            [110,112,113]]])
c.shape

(2, 2, 3)

In [0]:
c[0,...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [0]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [0]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [5]:
import numpy as np
def f(x,y):
  return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [6]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [7]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [13]:
a=np.floor(10*np.random.random((3,4)))
a

array([[9., 1., 0., 3.],
       [6., 8., 0., 2.],
       [2., 6., 7., 2.]])

In [14]:
a.shape

(3, 4)

In [15]:
a.ravel()

array([9., 1., 0., 3., 6., 8., 0., 2., 2., 6., 7., 2.])

In [16]:
a.reshape(6,2)

array([[9., 1.],
       [0., 3.],
       [6., 8.],
       [0., 2.],
       [2., 6.],
       [7., 2.]])

In [17]:
a.T

array([[9., 6., 2.],
       [1., 8., 6.],
       [0., 0., 7.],
       [3., 2., 2.]])

In [18]:
a.T.shape

(4, 3)

In [19]:
a.shape

(3, 4)

In [20]:
a

array([[9., 1., 0., 3.],
       [6., 8., 0., 2.],
       [2., 6., 7., 2.]])

In [22]:
a.resize((2,6))
a

array([[9., 1., 0., 3., 6., 8.],
       [0., 2., 2., 6., 7., 2.]])

In [23]:
a.reshape(3,-1)

array([[9., 1., 0., 3.],
       [6., 8., 0., 2.],
       [2., 6., 7., 2.]])

In [24]:
a=np.floor(10*np.random.random((2,2)))
a

array([[4., 7.],
       [4., 0.]])

In [25]:
b=np.floor(10*np.random.random((2,2)))
b

array([[4., 5.],
       [2., 8.]])

In [26]:
np.vstack((a,b))

array([[4., 7.],
       [4., 0.],
       [4., 5.],
       [2., 8.]])

In [27]:
np.hstack((a,b))

array([[4., 7., 4., 5.],
       [4., 0., 2., 8.]])

In [28]:
from numpy import newaxis
np.column_stack((a,b))

array([[4., 7., 4., 5.],
       [4., 0., 2., 8.]])

In [29]:
a=np.array([4.,2.])
b=np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [30]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [31]:
a[:,newaxis]

array([[4.],
       [2.]])

In [32]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [33]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [34]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [35]:
a=np.floor(10*np.random.random((2,12)))
a

array([[5., 6., 2., 2., 3., 0., 4., 3., 8., 5., 0., 1.],
       [4., 7., 3., 0., 2., 9., 2., 4., 5., 7., 2., 3.]])

In [36]:
np.hsplit(a,3)

[array([[5., 6., 2., 2.],
        [4., 7., 3., 0.]]), array([[3., 0., 4., 3.],
        [2., 9., 2., 4.]]), array([[8., 5., 0., 1.],
        [5., 7., 2., 3.]])]

In [37]:
np.hsplit(a,(3,4))

[array([[5., 6., 2.],
        [4., 7., 3.]]), array([[2.],
        [0.]]), array([[3., 0., 4., 3., 8., 5., 0., 1.],
        [2., 9., 2., 4., 5., 7., 2., 3.]])]

copies and views

In [38]:
a=np.arange(12)
b=a
b is a

True

In [39]:
b.shape=3,4
a.shape

(3, 4)

In [0]:
def f(x):
  print(id(x))
  id(a)

In [48]:
f(a)

139651311469712


view 

In [50]:
c=a.view()
c is a

False

In [51]:
c.base is a

True

In [52]:
c.flags.owndata

False

In [53]:
c.shape=2,6
a.shape

(3, 4)

In [54]:
c[0,4]=1234
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [0]:
s=a[:,1:3]

In [0]:
s[:]=10

In [59]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

deep copy

In [60]:
d=a.copy()
d is a

False

In [62]:
d.base is a


False

In [63]:
d[0,0]=9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])