<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/bo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([20,30,40,50])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [3]:
c=a-b
c

array([20, 29, 38, 47])

In [4]:
b**2

array([0, 1, 4, 9])

In [5]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [6]:
a<35

array([ True,  True, False, False])

In [7]:
A=np.array([[1,1],
           [0,1]])
B=np.array([[2,0],
            [3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [8]:
A@B

array([[5, 4],
       [3, 4]])

In [9]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [10]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [11]:
b+=a
b

array([[3.16063883, 3.22925264, 3.36852383],
       [3.70493588, 3.89081823, 3.32048295]])

In [0]:
a+=b


In [13]:
from numpy import pi
a=np.ones(3,dtype=np.int32)
b=np.linspace(0,pi,3)
b.dtype.name

'float64'

In [14]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [15]:
c.dtype.name

'float64'

In [16]:
d=np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [17]:
d.dtype.name

'complex128'

In [18]:
a=np.random.random((2,3))
a

array([[0.59192808, 0.89022708, 0.4714609 ],
       [0.22079979, 0.32409181, 0.48859424]])

In [19]:
a.sum()

2.987101899586298

In [20]:
a.min()

0.2207997946448177

In [21]:
a.max()

0.8902270776541363

In [22]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [24]:
b.min(axis=1)

array([0, 4, 8])

In [25]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])