<a href="https://colab.research.google.com/github/keerthanajayaprakash/internship/blob/master/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [2]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [3]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
u=np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [5]:
j=np.array([[0.0,-1.0],[1.0,0.0]])
j@j

array([[-1.,  0.],
       [ 0., -1.]])

In [6]:
np.trace(u)

2.0

In [7]:
y=np.array([[5.],[7.]])
np.linalg.solve(a,y)


array([[-3.],
       [ 4.]])

In [8]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

Python array examples

In [9]:
from array import*
my_array=array('i',[1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [10]:
my_array[1]

2

In [11]:
my_array[2]

3

In [12]:
my_array[0]

1

In [15]:
my_array.append(0)
my_array

array('i', [1, 2, 3, 4, 5, 6, 8, 0])

In [20]:
my_array.insert(2,2)
my_array

array('i', [0, 2, 2, 1, 2, 3, 4, 5, 6, 8, 0])

In [21]:
my_extend_array=array('i',[7,8,9,10])
my_array.extend(my_extend_array)
my_array

array('i', [0, 2, 2, 1, 2, 3, 4, 5, 6, 8, 0, 7, 8, 9, 10])

In [22]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 2, 2, 1, 2, 3, 4, 5, 6, 8, 0, 7, 8, 9, 10, 11, 12, 13])

In [31]:
my_array.remove(9)
my_array

array('i', [0, 2, 2, 1, 2, 3, 4, 5, 6, 8, 0, 7, 8, 11])

In [33]:
my_array.pop()

11

In [38]:
my_array

array('i', [0, 2, 2, 1, 2, 3, 4, 5, 6, 8, 0, 7, 8])

In [40]:
my_array.index(8)

9

In [41]:
my_array.reverse()
my_array

array('i', [8, 7, 0, 8, 6, 5, 4, 3, 2, 1, 2, 2, 0])

In [43]:
my_array.buffer_info()

(139651312646952, 13)

In [45]:
my_array.count(8)

2

In [49]:
my_char_array=array('i',[ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

array('i', [103, 101, 101, 107])

In [50]:
my_char_array.tostring()

b'g\x00\x00\x00e\x00\x00\x00e\x00\x00\x00k\x00\x00\x00'

In [51]:
c=my_array.tolist()
c

[8, 7, 0, 8, 6, 5, 4, 3, 2, 1, 2, 2, 0]

In [52]:
my_char_array.fromstring("stuff")
my_char_array

ValueError: ignored

prime number generator

In [76]:
def is_prime(n):
   for i in range(5, n):
       if n % i == 0:
           return False
   return True
  
n= input("Enter a number:")
for x in range(5,int(n)):
    if is_prime(x):
       print(x, "is a prime")
    else:
       print(x, "is not prime")

Enter a number:10
5 is a prime
6 is a prime
7 is a prime
8 is a prime
9 is a prime


In [108]:
 n = input("Enter a number:")
#for x in int(n):
if is_prime (int(n)):
         print(n,"is prime")
else:
         print(n, "is not prime")

Enter a number:12
12 is not prime


In [110]:
minimum = int(input("enter the minimum value :"))
maximum = int(input("enter the maximum value :"))

for number in range(minimum,maximum+1):
    if(number % 2 == 0):
       print("{0}".format(number))

enter the minimum value :1
enter the maximum value :100
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
